baseURL: "https://himanshuvashist.in"
languageCode: "en-us"
title: "Himanshu Profile"
theme: hugo-profile

Paginate: 3
# disqusShortname: h
googleAnalytics: G-ZFDNTLMX01

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Himanshu's Profile"
  description: Himanshu vashist personal portfolio website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/logo.svg"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

    # font:
    #   fontSize: 1.5rem # default: 1rem
    #   fontWeight: 500 # default: 400
    #   lineHeight: 1 # default: 1.5
    #   textAlign: right # default: left

    # color preference
    # color:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    #   primaryColor:
    #   secondaryColor:

    #   darkmode:
    #     textColor:
    #     secondaryTextColor:
    #     backgroundColor:
    #     secondaryBackgroundColor:
    #     primaryColor:
    #     secondaryColor:

    # If you want to customize the menu, you can change it here
    # navbar:
    #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/images/logo.svg" # Logo for the brand | default is the favicon variable
    #   brandName: "Profile" # Brand name for the brand | default is the title variable

    #   menus:
    #     disableAbout: true
    #     disableExperience: true
    #     disableEducation: true
    disableProjects: true
    disableAchievements: true
    disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Himanshu."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /images/Person.png
    button:
      enable: true
      name: "Resume"
      url: "https://github.com/himanshuvashist/resume/raw/main/Resume_React_Developer_Himanshu_Vashist.docx"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/himanshuvashist
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/himanshuvashist
        - icon: fab fa-twitter
          url: https://twitter.com/tipsy_ninja
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/PersonSecond.png"
    content: |-
       I am a software Engineer with a passion for web/app development. I have a background in computer science and mathematics, and I have a strong interest in technology. I am currently working at [32nd](https://32nd.com) as a React/React Native Developer. My work involves collaborating on innovative solutions for businesses, optimizing user experiences, and maintaining high coding standards. I'm dedicated to building web/native applications that are not just functional but also intuitive and visually appealing.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React native"
        - "Zustand"

  # Experience
  experience:
    enable: true
    items:
    
      - job: "React/React Native Developer"
        company: "32nd"
        companyUrl: "https://32nd.com/"
        date: "Sep 2022 - current"
        featuredLink:
          enable: false
          url: "https://32nd.com/"
        info:
          enable: true
          content: I am working as React/React Native developer at 32nd.
        content: |
          -  Collaborated closely with cross-functional teams to align product development with business goals.
          -  Improved the architecture and maintainability of products, resulting in increased efficiency and reduced technical debt.
          -  Implemented changes to streamline business operations, optimizing user experiences.
          -  Utilized debugging tools and maintained documentation.
          -  Actively participated in code reviews and ensured high-quality standards.

          
      - job: "Software Engineer"
        company: "Ikonwork"
        companyUrl: "https://ikonwork.com"
        date: "Nov 2021 - Sep 2022"
        featuredLink:
          enable: true
          name: "Dridges"
          url: "https://Dridges.com"
        content: |
          I am currently working as a software developer at [Ikonwork](https://Ikonwork.com) in Faridabad, Haryana, India. I am currently working on a project that will be used to help HR find the candidates using our ATS(Application Tracking System).

          Resposiblities - 
          - Responsible for adding new features to product and manage issues of complex and technical in nature with varying degrees of priority.
          - Assisted implementing changes and integrating requested elements to streamline business
          operations.
          - Plan and find technical solutions for new feature and coordinate with my team to execute it.
          - Ran debugging tools such as Firebug and Chrome Inspector to eliminate flaws and glitches.
          - Applied latest emerging technology, software and project application trends to update and maintain
          site applicability.
          - Improved code writing of team by introducing linter and prevented unnecessary code going into production with husky. Time we spend on resolving conflicting code had reduced significantly, it <strong> improved my team's overall efficiency by 12-15%.</strong>
          - Oversaw technical issues and troubleshooting requests to resolve surfaced problems

      - job: "Software Engineer"
        company: "SocialPilot"
        companyUrl: "https://www.socialpilot.co/"
        date: "Dec 2020 - June 2021"
        featuredLink:
          enable: false
          url: "https://www.socialpilot.co/"
        info:
          enable: true
          content: I worked as a React developer at SocialPilot.
        content: |
          - Worked as ReactJs developer, was responsible for upgrading UI mainly using ReactJs, redux, react-bootstrap and maintaining whole code base.
          - Conducted testing and review of website design for responsiveness, clarity and effectiveness.
          - Provided ongoing efficiency and maintenance and patching on website interface to maintain viability.
          - Involved in Code Review with GITLAB and debugging using chrome dev tools.
  


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Technology in Computer Science"
        school:
          name: "Rawal Institute of Engineering & Technology"
          url: "http://riet.in/"
        # date: "2021"
      - title: "Udacity Nanodegree Program Graduate"
        school:
          name: "Udacity"
          url: "https://graduation.udacity.com/confirm/JJDVN3ZG"

        # GPA: "3.9 out of 5.0"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "High School"
        school:
          name: "Rawal International School"
          url: "http://www.rawalinternationalschool.com/"
        # GPA: "4.2 out of 5.0"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  achievements:
    # enable: true
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    # enable: true
    items:
      - title: lesemMe
        content: Two Minute Reads
        image: https://notioly.com/wp-content/uploads/2022/04/123.Website-builder.png
        featured:
          name: Live
          link: https://lesenme.com
        badges:
          - "Javascript"
          - "ReactJs"
          - "Gatsby"

  #Contact
  contact:
    # enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    # email: @gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/himanshuvashist
      linkedin: https://linkedin.com/in/himanshuvashist
      twitter: https://twitter.com/tipsy_ninja
      # instagram: https://instagram.com
      # facebook: https://facebook.com
